
# Site settings
title: Eventos Pokémon Go Cali

#What is the name of the events or talks you would like to host? (Example Brownbags, Talks, Lighting Talks)
event_label: Events

description: > # this means to ignore newlines until "baseurl:"
   Pokemon Go Cali no es responsable de cualquier hecho inesperado que ocurra en el encuentro
   (Solo nos encargamos de Divulgar y promover los lugares y fechas de encuentro que los fans de la página proponen.)
   Comparte La información a quienes interese.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://eventos.pokemongocali.com" # the base hostname & protocol for your site

#These settings might be able to go?
author: CreaDev.co
twitter_username: creadev_co
github_username:  creadevco
company_name: CreaDev

# Build settings
markdown: kramdown

#Have to show future posts for future events.
future: true

permalink: /event/:title.html
